

{
    "count": 12,
    "next": null,
    "previous": null,
    "results": [
        {
            "type": "barbarian",
            "class": "barbarian",
            "desc": "### Rage \n \nIn battle, you fight with primal ferocity. On your turn, you can enter a rage as a bonus action. \n \nWhile raging, you gain the following benefits if you aren't wearing heavy armor: \n \n* You have advantage on Strength checks and Strength saving throws. \n* When you make a melee weapon attack using Strength, you gain a bonus to the damage roll that increases as you gain levels as a barbarian, as shown in the Rage Damage column of the Barbarian table. \n* You have resistance to bludgeoning, piercing, and slashing damage. \n \nIf you are able to cast spells, you can't cast them or concentrate on them while raging. \n \nYour rage lasts for 1 minute. It ends early if you are knocked unconscious or if your turn ends and you haven't attacked a hostile creature since your last turn or taken damage since then. You can also end your rage on your turn as a bonus action. \n \nOnce you have raged the number of times shown for your barbarian level in the Rages column of the Barbarian table, you must finish a long rest before you can rage again. \n \n### Unarmored Defense \n \nWhile you are not wearing any armor, your Armor Class equals 10 + your Dexterity modifier + your Constitution modifier. You can use a shield and still gain this benefit. \n \n### Reckless Attack \n \nStarting at 2nd level, you can throw aside all concern for defense to attack with fierce desperation. When you make your first attack on your turn, you can decide to attack recklessly. Doing so gives you advantage on melee weapon attack rolls using Strength during this turn, but attack rolls against you have advantage until your next turn. \n \n### Danger Sense \n \nAt 2nd level, you gain an uncanny sense of when things nearby aren't as they should be, giving you an edge when you dodge away from danger. \n \nYou have advantage on Dexterity saving throws against effects that you can see, such as traps and spells. To gain this benefit, you can't be blinded, deafened, or incapacitated. \n \n### Primal Path \n \nAt 3rd level, you choose a path that shapes the nature of your rage. Choose the Path of the Berserker or the Path of the Totem Warrior, both detailed at the end of the class description. Your choice grants you features at 3rd level and again at 6th, 10th, and 14th levels. \n \n### Ability Score Improvement \n \nWhen you reach 4th level, and again at 8th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1. As normal, you can't increase an ability score above 20 using this feature. \n \n### Extra Attack \n \nBeginning at 5th level, you can attack twice, instead of once, whenever you take the Attack action on your turn. \n \n### Fast Movement \n \nStarting at 5th level, your speed increases by 10 feet while you aren't wearing heavy armor. \n \n### Feral Instinct \n \nBy 7th level, your instincts are so honed that you have advantage on initiative rolls. \n \nAdditionally, if you are surprised at the beginning of combat and aren't incapacitated, you can act normally on your first turn, but only if you enter your rage before doing anything else on that turn. \n \n### Brutal Critical \n \nBeginning at 9th level, you can roll one additional weapon damage die when determining the extra damage for a critical hit with a melee attack. \n \nThis increases to two additional dice at 13th level and three additional dice at 17th level. \n \n### Relentless Rage \n \nStarting at 11th level, your rage can keep you fighting despite grievous wounds. If you drop to 0 hit points while you're raging and don't die outright, you can make a DC 10 Constitution saving throw. If you succeed, you drop to 1 hit point instead. \n \nEach time you use this feature after the first, the DC increases by 5. When you finish a short or long rest, the DC resets to 10. \n \n### Persistent Rage \n \nBeginning at 15th level, your rage is so fierce that it ends early only if you fall unconscious or if you choose to end it. \n \n### Indomitable Might \n \nBeginning at 18th level, if your total for a Strength check is less than your Strength score, you can use that score in place of the total. \n \n### Primal Champion \n \nAt 20th level, you embody the power of the wilds. Your Strength and Constitution scores increase by 4. Your maximum for those scores is now 24.",
            "hit_dice": "12",
            "prof_saving_throws": {"Strength": 0, "Constitution": 0},
            "prof_skills": "Animal Handling, Athletics, Intimidation, Nature, Perception, Survival",
            "table": "| Level  | Proficiency Bonus | Features                      | Rages     | Rage Damage | \n|--------|-------------------|-------------------------------|-----------|-------------| \n| 1st    | +2                | Rage, Unarmored Defense       | 2         | +2          | \n| 2nd    | +2                | Reckless Attack, Danger Sense | 2         | +2          | \n| 3rd    | +2                | Primal Path                   | 3         | +2          | \n| 4th    | +2                | Ability Score Improvement     | 3         | +2          | \n| 5th    | +3                | Extra Attack, Fast Movement   | 3         | +2          | \n| 6th    | +3                | Path feature                  | 4         | +2          | \n| 7th    | +3                | Feral Instinct                | 4         | +2          | \n| 8th    | +3                | Ability Score Improvement     | 4         | +2          | \n| 9th    | +4                | Brutal Critical (1 die)       | 4         | +3          | \n| 10th   | +4                | Path feature                  | 4         | +3          | \n| 11th   | +4                | Relentless                    | 4         | +3          | \n| 12th   | +4                | Ability Score Improvement     | 5         | +3          | \n| 13th   | +5                | Brutal Critical (2 dice)      | 5         | +3          | \n| 14th   | +5                | Path feature                  | 5         | +3          | \n| 15th   | +5                | Persistent Rage               | 5         | +3          | \n| 16th   | +5                | Ability Score Improvement     | 5         | +4          | \n| 17th   | +6                | Brutal Critical (3 dice)      | 6         | +4          | \n| 18th   | +6                | Indomitable Might             | 6         | +4          | \n| 19th   | +6                | Ability Score Improvement     | 6         | +4          | \n| 20th   | +6                | Primal Champion               | Unlimited | +4          | ",

            "feats": 
                {"1": "Rage, Unarmored Defense",
                 "2": "Reckless Attack, Danger Sense",
                 "3": "Primal Path - Frenzy",
                 "4": "Ability Score Improvement",
                 "5": "Extra Attack, Fast Movement",
                 "6": "Path feature - Mindless Rage",
                 "7": "Feral Instinct",
                 "9": "Brutal Critical (1 die)",
                 "10": "Path feature - Mindless Rage",
                 "11": "RelentlessRage",
                 "13": "Brutal Critical (2 dice)",
                 "14": "Path feature",
                 "15": "Persistent Rage",
                 "17": "Brutal Critical (3 dice)",
                 "18": "Indomitable Might",
                 "20": "Primal Champion"
                },

            "growth_table":
                {"1": { "rages": 2,
                        "rage_damage": 2},
                 "2": { "rages": 2,
                        "rage_damage": 2},
                 "3": { "rages": 3,
                        "rage_damage": 2},
                 "4": { "rages": 3,
                        "rage_damage": 2},
                 "5": { "rages": 3,
                        "rage_damage": 2},
                 "6": { "rages": 4,
                        "rage_damage": 2},
                 "7": { "rages": 4,
                        "rage_damage": 2},
                 "8": { "rages": 4,
                        "rage_damage": 2,
                        "Ability Score Improvement": 2},
                 "9": { "rages": 4,
                        "rage_damage": 3},
                 "10": {"rages": 4,
                        "rage_damage": 3},
                 "11": {"rages": 4,
                        "rage_damage": 3},
                 "12": {"rages": 5,
                        "rage_damage": 3,
                        "Ability Score Improvement": 2},
                 "13": {"rages": 5,
                        "rage_damage": 3},
                 "14": {"rages": 5,
                        "rage_damage": 3}  , 
                 "15": {"rages": 5,
                        "rage_damage": 3},
                 "16": {"rages": 5,
                        "rage_damage": 4,
                        "Ability Score Improvement": 2},
                 "17": {"rages": 6,
                        "rage_damage": 4},
                 "18": {"rages": 6,
                        "rage_damage": 4},
                 "19": {"rages": 6,
                        "rage_damage": 4,
                        "Ability Score Improvement": 2},
                 "20": {"rages": "unlimited",
                        "rage_damage": 4,
                        "strenght": 4,
                        "constitution": 4}},
           
            "spellcasting_ability": "",
            "subtypes_name": "Paths",
            "archetypes": [
                {
                    "name": "Path of the Berserker",
                    "slug": "path-of-the-berserker",
                    "desc": "For some barbarians, rage is a means to an end- that end being violence. The Path of the Berserker is a path of untrammeled fury, slick with blood. As you enter the berserker's rage, you thrill in the chaos of battle, heedless of your own health or well-being. \n \n##### Frenzy \n \nStarting when you choose this path at 3rd level, you can go into a frenzy when you rage. If you do so, for the duration of your rage you can make a single melee weapon attack as a bonus action on each of your turns after this one. When your rage ends, you suffer one level of exhaustion (as described in appendix A). \n \n##### Mindless Rage \n \nBeginning at 6th level, you can't be charmed or frightened while raging. If you are charmed or frightened when you enter your rage, the effect is suspended for the duration of the rage. \n \n##### Intimidating Presence \n \nBeginning at 10th level, you can use your action to frighten someone with your menacing presence. When you do so, choose one creature that you can see within 30 feet of you. If the creature can see or hear you, it must succeed on a Wisdom saving throw (DC equal to 8 + your proficiency bonus + your Charisma modifier) or be frightened of you until the end of your next turn. On subsequent turns, you can use your action to extend the duration of this effect on the frightened creature until the end of your next turn. This effect ends if the creature ends its turn out of line of sight or more than 60 feet away from you. \n \nIf the creature succeeds on its saving throw, you can't use this feature on that creature again for 24 hours. \n \n##### Retaliation \n \nStarting at 14th level, when you take damage from a creature that is within 5 feet of you, you can use your reaction to make a melee weapon attack against that creature.",
                    "document__slug": "wotc-srd",
                    "document__title": "Systems Reference Document",
                    "document__license_url": "http://open5e.com/legal"
                }
            ],
            "document__slug": "wotc-srd",
            "document__title": "Systems Reference Document",
            "document__license_url": "http://open5e.com/legal"
        }
    ]
}